# documentation at https://docs.aws.amazon.com/codebuild/latest/userguide/build-spec-ref.html
version: 0.2

proxy:
  upload-artifacts: yes
  logs: yes

batch:
  fast-fail: true
        
phases:
  pre_build:
    commands:
      - echo "Installing dependencies..."
      - npm install
  build:
    commands:
      - npm run build
      
